# Generated by Django 4.1.3 on 2024-04-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appin", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="datas", old_name="Age", new_name="Number",),
    ]
